import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import { useWallet } from '@solana/wallet-adapter-react'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { ArrowSquareOut } from '@phosphor-icons/react'

const WalletMultiButtonDynamic = dynamic(
  async () => (await import('@solana/wallet-adapter-react-ui')).WalletMultiButton,
  { ssr: false }
)

const WalletDisconnectButtonDynamic = dynamic(
  async () => (await import('@solana/wallet-adapter-react-ui')).WalletDisconnectButton,
  { ssr: false }
)

export default function Home() {
  const wallet = useWallet()
  const [connected, setConnected] = useState(false)
  const [degenScore, setDegenScore] = useState(0)
  const [nameTags, setNameTags] = useState([])

  useEffect(() => {
    const analyzeWallet = async (address) => {
      const res = await axios.post("/api/analyze_wallet", {
        wallet_address: address
      })
      setDegenScore(res.data.degen_score)
      setNameTags(res.data.name_tags)
    }

    if (wallet.connected) {
      setConnected(true)
      analyzeWallet(wallet.publicKey.toString())
    }
    else {
      setConnected(false)
    }
  }, [wallet])

  return (
    <div className={styles.container}>
      <Head>
        <title>Coinsense - Analyse your Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.nav_title}>
        <h1>C🤪INSENSE!</h1>
      </div>
      {connected ? (
        <div className={styles.box}>
          <p className={styles.degen_score}>{degenScore}<span className={styles.total_score}>/700</span></p>
          <p className={styles.box_title}>DEGEN SCORE</p>
          {nameTags.length > 0 ? <p className={styles.box_desc}>You are a <span>{nameTags[0]}</span>. <span>A {nameTags[1]}</span>, if you will.</p> : "Loading..."}
          <div className={styles.buttons}>
            <WalletDisconnectButtonDynamic className={styles.auth_btn} />
            <button onClick={() => {
              window.open(`https://translator.shyft.to/address/${wallet.publicKey.toString()}`, '_blank').focus();
            }}>
              <ArrowSquareOut size={28} color="white" weight="light" />
            </button>
          </div>
        </div>
      ) :
        <div className={styles.box}>
          <p className={styles.cta}>Connect your wallet to get started!</p>
          {/* <button>Connect</button> */}
          <WalletMultiButtonDynamic children="Connect" />
        </div>}
    </div>
  )
}
